app/urls.py
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="home"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>', views.add_product, name="add"),
    path('delete/<int:product_id>', views.delete_product, name="delete"),
    path('subtract/<int:product_id>', views.delete_one_product, name="subtract"),
    path('clear/', views.empty_cart, name="clear"),
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name="shop"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #include app urls
    path('', include('app.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('shop/', include('shop.urls')),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),

    path('authentication/', include('authentication.urls')),

]

shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 50)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)
    
    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField( upload_to="shop", null = True, blank = True )
    price = models.FloatField()
    stock = models.BooleanField(default = True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render, redirect
from .cart import Cart
from shop.models import Product

# Create your views here.

def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id = product_id)
    cart.add(product = product)
    return redirect('shop')

def delete_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id = product_id)
    cart.delete(product = product)
    return redirect('shop')

def delete_one_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id = product_id)
    cart.delete_one(product = product)
    return redirect('shop')

def empty_cart(request):
    cart = Cart(request)
    cart.clean_cart()
    return redirect('shop')

shop/views.py
from django.shortcuts import render, HttpResponse
from .models import Product

# Create your views here.

def shop(request):
    products = Product.objects.all()
    return render(request, 'shop/shop.html', {'products':products})

shop/templates/cart/widget.html
<table class="table table-info">
    <thead class="table-primary">Detail</thead>
    <tr class="table-info">
        <th>Products</th>
        <th>Cantidad</th>
        <th>Sub total</th>
    </tr>
    <tbody class="table-info">
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr>
                    <th>{{value.name}}</th>
                    <th>{{value.lot}}</th>
                    <th class="text-right">{{value.price}} $</th>
                    <th>
                        <a href="{% url 'cart:add' value.product_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'cart:subtract' value.product_id %}" class="btn btn-sm btn-danger">-</a>
                    </th>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="text-center alert alert-danger">Aún no tienes productos en tu carro de compras</div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                Total
            </th>
            <th class="text-right">
                {{amount_total}} $
            </th>
        </tr>

        {% if request.session.cart.items %}
        <tr>
            <td colspan="4" style="text-align:center">
            <a href="../order" class="btn bg-cart">
                <i class="mr-2 fa fa-cart-plus"></i> Get Order
            </a>
            </td>
        </tr>
        {% endif %}

    </tfoot>
</table>